name: nfc_card
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+3

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  basic_utils: ^5.7.0
  logger: ^2.1.0
  nfc_manager:
    git: https://github.com/TamilKannanCV/flutter-nfc-manager.git
  lottie: ^3.1.0
  intl: ^0.19.0
  facebook_audience_network: ^1.0.1

flutter_gen:
  integrations:
    lottie: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Kredit
      fonts:
        - asset: assets/fonts/kredit.ttf
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/dm_serif_display_regular.ttf
  assets:
   - assets/images/
   - assets/lotties/
